prgrms-web-devcourse-final-project/WEB5_6_GCC_BE

- src/main/java/com/honlife/core/app/controller/badge/BadgeController.java
- src/main/java/com/honlife/core/app/controller/member/MemberController.java
- src/main/java/com/honlife/core/infra/response/ResponseCode.java
- 여러 상황을 가정하여, 발생할 수 있을 에러에 대비해 응답코드를 수정 및 추가하였습니다.
- Item, Quest 등 식별자로 직접적인 조회가 진행될 수 있는 영역에 대한 404코드 추가
- Item, Quest 등 중복 요청이 발생할 수 있는 영역에 대한 409 코드 추가
- 그 외) 기존의 한국어로 되어있던 에러메세지를 영어로 변환
- 매우 많은 충돌이 일어날 것으로 예상됩니다. 충돌에 대비하세요(?)
> :sparkles: add: new response codes

- src/main/java/com/honlife/core/app/model/member/domain/MemberQuest.java
- src/main/java/com/honlife/core/app/model/member/service/MemberQuestService.java
- src/main/resources/data.sql
> Refactor: Replace name

- src/main/resources/data.sql
- Member 엔티티 구조 변화에 따른 샘플 데이터 수정
> :card_file_box: update: add is_verified field to sample data

- src/main/java/com/honlife/core/infra/response/ResponseCode.java
- 멤버와 관련된 409코드를 추가하였습니다.
- 도메인 관련 주석을 추가하였습니다.
- 에러코드 4091 : "이미 존재하는 회원입니다" 코드를 추가하였습니다.
- ResponseCode 상단에 HTTPStatus Code 뒤의 번호를 어떻게 붙이면 좋을지에 대해 도메인 별로 번호를 지정하여 주석을 달아놓았으니, 나중에 추가해야하실 분은 참고하시면 될 것 같습니다.
- 401은 인증관련 에러이기에 제외입니다.
> :recycle: add: exists member conflict response code

- src/main/java/com/honlife/core/app/controller/badge/BadgeController.java
제곧내
파라미터 이름 오기입으로 인한 오류를 해결하였습니다
> [swagger] 뱃지 수령 오류 해결

- src/main/java/com/honlife/core/app/controller/item/ItemController.java
- src/main/java/com/honlife/core/app/controller/item/payload/ItemResponse.java
- src/main/java/com/honlife/core/app/controller/member/MemberItemController.java
- src/main/java/com/honlife/core/app/controller/member/payload/MemberItemResponse.java
Item 조회 시 응답에 description 추가
✨ feat: Add description to response structure and controller
-  Controller 와 Response에 description을 추가하였습니다
> [Swagger] Item 조회 시 응답에 description 추가

- src/main/java/com/honlife/core/app/controller/member/MemberController.java
비밀번호를 확인하는 API를 추가하였습니다.
홍길동 씨로 로그인 했을 때 비밀번호를 확인하는 API를 추가하였습니다.
> [swagger] 비밀번호 확인 API 추가

- src/main/java/com/honlife/core/app/controller/member/MemberController.java
- src/main/java/com/honlife/core/app/controller/member/payload/MemberWithdrawRequest.java
- src/main/java/com/honlife/core/app/model/withdraw/code/WithdrawType.java
회원 탈퇴 부분을 수정하였습니다.
잘못된 validation으로 인해 발생하는 오류를 수정하였습니다.
회원 탈퇴 사유를 피그마 페이지와 동일하게 만들었습니다.
withdrarwType enum 값들 괜찮나여
> [Swagger] 회원 탈퇴 수정

- src/main/java/com/honlife/core/app/controller/member/MemberController.java
- src/main/java/com/honlife/core/app/model/member/service/MemberService.java
> 🚑 Fix: Resolve circular dependency between services

- src/main/java/com/honlife/core/app/model/category/domain/Category.java
category_sequence 변경 중 GeneratedValue도 같이 고치지 않아 생기는 오류를 해결하였습니다.
카테고리 GeneratedValue 를 바꾸지 않아서 오류가 발생하여 실행이 안 되는 버그를 해결하였습니다.
> Category - entity id GeneratedValue 오류 수정

- src/main/java/com/honlife/core/app/controller/member/MemberController.java
Swgger member page를 완성하였습니다.
dev 브랜치에서 실행한 것과 비교하여 제대로 결과물이 반환되는지 확인하였습니다.
> [swagger] member 완료

- src/main/java/com/honlife/core/app/controller/member/MemberItemController.java
MemberItem 실제 구현 함에 따라 Swagger API 문서 수정하였습니다.
📝 docs: Update memberItem Swagger API and descriptions
- 회원이 현재 장착 중인 아이템을 조회하는 API는 삭제하였습니다.
- 아이템 상태 변경 API를 -> 아이템 장착,해제로 엔드 포인트를 구분하였습니다.
> [Swagger] MemberItem 조회 및 장착아이템 상태 변경 수정

- src/main/java/com/honlife/core/app/controller/admin/item/AdminItemController.java
- src/main/java/com/honlife/core/app/controller/admin/item/payload/AdminItemResponse.java
관리자 아이템 조회 시 응답 형식 추가 하였습니다.
📝 Docs: Update Swagger API documentation
- 설명, 삭제& 활성화 여부 응답 추가하였습니다.
> [Swagger]관리자 아이템 조회 시 응답 형식 추가 

- src/main/java/com/honlife/core/app/model/routine/domain/Routine.java
category 삭제 시에 category를 null 로 처리하기 위해 칼럼을 수정하였습니다.
routine.category를 nullable로 변경하였습니다.
> Routine - category 칼럼 nullable로 수정

- src/main/java/com/honlife/core/app/controller/category/CategoryController.java
- src/main/java/com/honlife/core/app/controller/category/payload/CategoryWithParentResponse.java
- src/main/java/com/honlife/core/app/controller/category/payload/ChildCategoryResponse.java
- src/main/java/com/honlife/core/app/controller/category/wrapper/CategoryWrapper.java
기능 구현되며 수정된 응답구조와 동일하게 응답을 변경하였습니다.
전체조회, 단건조회의 응답 구조가 변경되었습니다.
> [Swagger] category 조회 응답 구조 기능 구현과 동일하게 변경

- src/main/java/com/honlife/core/app/controller/admin/item/AdminItemController.java
- src/main/java/com/honlife/core/app/controller/admin/item/payload/AdminCreateItemRequest.java
- src/main/java/com/honlife/core/app/model/item/domain/Item.java
- src/main/java/com/honlife/core/app/model/item/service/AdminItemService.java
- src/main/java/com/honlife/core/app/model/item/service/ItemService.java
관리자 아이템 생성 API를 구현 하였습니다.
✨ Feat: Add API create Item in AdminController
✨ Feat: Add Request for CreateItem
- 생성 시 요청 Rquest를 따로 추가하였습니다.
🐛 Fix: Add Annotation in Entity
:sparkles: Feat: Implement admin Item Create logic
> 관리자 아이템 생성 API 구현

- src/main/java/com/honlife/core/app/model/member/service/MemberService.java
멤버 업데이트 시 닉넴 체크
닉네임이 존재하는지 확인하며 이미 존재 시 409에러를 리턴하도록 수정하였습니다.
> 멤버 업데이트 시 닉넴 체크

- src/main/java/com/honlife/core/app/model/member/service/MemberService.java
> 🚑 닉네임 변경이 없을 시 중복검사 통과

- src/main/java/com/honlife/core/app/model/badge/repos/BadgeRepository.java
- src/main/java/com/honlife/core/app/model/badge/service/BadgeProgressService.java
알림 코드를 기반으로 업적 달성 알림을 추가하였습니다.
업적 달성 알림 로직을 추가하였습니다.
제발 됐으면 좋겠습니다.
> 업적 - 업적 달성 알림 추가

- src/main/java/com/honlife/core/app/model/category/service/CategoryService.java
> 🚑 카테고리 생성 수정 시 기본 카테고리에 접근하지 못하도록 수정

- src/main/java/com/honlife/core/app/model/websocket/service/NotificationSocketService.java
- src/main/java/com/honlife/core/infra/config/security/SecurityConfig.java
소켓에서 / 를 안붙여서 나는 오류를 해결했습니다
- url주소 바뀌었습니다
- 그리고 시큐리티쪽 웹소켓부분은 다 허용되도록 추가했습니다
> socket - 소켓 오류 고쳤습니다

- src/main/java/com/honlife/core/app/model/websocket/service/NotificationSocketService.java
- src/main/java/com/honlife/core/infra/config/WebSocketConfig.java
- src/main/java/com/honlife/core/infra/config/security/SecurityConfig.java
> Refactor/fixsocket - 보안 경로 이슈

- src/main/java/com/honlife/core/app/model/member/service/MemberPointService.java
- src/main/java/com/honlife/core/app/model/routine/service/RoutineService.java
- src/main/java/com/honlife/core/infra/config/WebSocketConfig.java
> Refactor/logic - 로직 수정

- src/main/java/com/honlife/core/infra/config/WebSocketConfig.java
> 🚑Refactor/logic -이 설정부분이 추가 되야할거같아서 설정 하나 추가 합니다

- src/main/java/com/honlife/core/app/model/routine/dto/RoutineItemDTO.java
- src/main/java/com/honlife/core/app/model/routine/service/RoutineService.java
> Refactor/logic - 프론트에서 필요하시다고 했던 repeatTerm 필드 추가 했습니다

- src/main/java/com/honlife/core/app/controller/member/MemberController.java
- src/main/java/com/honlife/core/app/controller/member/payload/MemberUpdateRequest.java
- src/main/java/com/honlife/core/app/model/member/service/MemberService.java
> 🚑 멤버 정보 업데이트에 이름을 받지 않도록 수정

- src/main/java/com/honlife/core/app/controller/notification/SseController.java
> :recycle: refactor : refactor sse logic

- src/main/java/com/honlife/core/app/controller/notification/SseController.java
> :recycle: refactor: delete annotation
