src/main/java/com/honlife/core/app/controller/auth/AuthController.java
src/main/java/com/honlife/core/app/controller/auth/payload/SignupRequest.java
src/main/java/com/honlife/core/infra/config/security/SecurityConfig.java

- 프론트의 요청에 따라 이메일 및 닉네임 중복검사 API를 추가하였고, 회원가입시 관심 카테고리를 배열로 받을 수 있도록 필드를 추가하였습니다.
- 중복검사 API를 추가하였습니다.
- RequestParam으로 email 또는 nickname을 받으며, 두 파라메터는 모두 `required=false`입니다.
- 둘 모두 들어오거나 둘 모두 없다면 Bad Request를 응답합니다.
- 회원가입시에 RequestBody로 사용되던 `SignupRequest` 에서 관심 카테고리의 배열을 입력받을 수 있는 `categoryInterests` 필드를 추가하였습니다.

✨ AuthController 수정 : 중복검사 API 추가 및 회원가입 Request 수정

---

src/main/java/com/honlife/core/app/controller/member/MemberBadgeController.java
src/main/java/com/honlife/core/app/controller/member/payload/MemberBadgeResponse.java

회원 소유 업적 조회 API 추가하였습니다.
url, SecurityRequirement , tag 를 작성하였습니다.
회원 소유 업적 조회 API를 추가하였습니다.

회원이 소유한 업적 조회 API 추가

---

src/main/java/com/honlife/core/app/controller/badge/BadgeController.java

Badge에서 단건 조회와 전체 조회를 분리하였습니다.
분리하여 단건 조회는 key를 pathVaraible로 받습니다.

♻️ refactor: split badge list and single lookup into separate APIs

---

src/main/java/com/honlife/core/app/controller/member/MemberController.java
src/main/java/com/honlife/core/app/controller/member/payload/MemberPayload.java
src/main/java/com/honlife/core/app/controller/member/payload/MemberResponse.java
src/main/java/com/honlife/core/app/controller/member/payload/MemberUpdatePasswordRequest.java
src/main/java/com/honlife/core/app/controller/member/payload/MemberWithdrawRequest.java

- 회원 정보 관련 API들을 추가 및 수정하였습니다.
- 비밀번호 변경시 사용될 API를 추가하였습니다.
- 요청시 RequestBody로 사용될 DTO를 추가하였습니다.
- 회원정보 변경시 사용될 API를 추가하였습니다.
- 요청시 RequestBody로 사용될 DTO를 추가하였습니다.
- 해당 DTO에서 이름과 닉네임은 필수로 받도록 하였습니다.
- 회원탈퇴 요청시 사용될 API를 추가하였습니다.
- 요청시 RequestBody로 사용될 DTO를 추가하였습니다.
- 해당 DTO에서 타입을 필수로 받도록 하였으며, 사유가 '기타'일 때, 탈퇴이유 사용자 입력을 받기 위한 필드를 추가하였습니다.
- 기존의 전체 멤버 조회 API는 회원에게는 필요없다고 판단되어 삭제하였습니다.
- 회원정보 조회, 회원정보 수정에 동일한 필드가 사용되기때문에 굳이 둘로 나누는 것 보단, 재사용하는게 좋을 것 같아, Payload로 네이밍 하고 함께 사용하도록 하였습니다.

MemberController API 추가 및 수정

---

src/main/java/com/honlife/core/app/controller/category/InterestCategoryController.java
src/main/java/com/honlife/core/app/controller/category/payload/InterestCategoryPayload.java
src/main/java/com/honlife/core/app/controller/category/payload/InterestCategoryResponse.java
src/main/java/com/honlife/core/app/controller/category/payload/UpdateInterestCategoryRequest.java

관심 카테고리 조회와 업데이트 API를 작성하였습니다.
tag, securityRequirement, url 경로를 설정하였습니다.
로그인 한 회원의 관심 카테고리 정보를 가져오는 API를 추가하였습니다.
로그인 한 회원의 관심 카테고리 정보를 수정하는 API를 추가했습니다.
쓰다보니까 이거 member 쪽으로 들어가는 게 낫지 않나 싶은데 의견 주시면 감사드리겠습니다.

관심 카테고리 API 추가

---

src/main/java/com/honlife/core/app/controller/routine/RoutineController.java
src/main/java/com/honlife/core/app/model/routine/code/RepeatType.java

RepeatType enum에서 NONE 옵션을 제거하여 루틴의 정의를 명확히 했습니다.
루틴은 반복적인 습관을 의미하므로 일회성 작업(TODO)과 구분하여 서비스의 핵심 개념을 정립했습니다.
- RepeatType enum에서 NONE 옵션 제거
- 루틴을 반복적인 습관으로 정의하고 일회성 작업과 명확히 구분
- 루틴의 핵심 개념 정립: DAILY, WEEKLY, MONTHLY, CUSTOM만 유지
- RepeatType에서 NONE 제거가 기존 비즈니스 로직에 미치는 영향 검토 필요
- 루틴과 TODO의 구분이 서비스 방향성과 일치하는지 의견 부탁드립니다
- 혼라이프의 "루틴을 통한 캐릭터 성장" 컨셉에 더 부합하는 변경인지 확인해주세요

repeatType 수정

---

src/main/java/com/honlife/core/app/model/member/domain/Member.java
src/main/java/com/honlife/core/app/model/member/model/MemberDTO.java

- 회원가입, 비밀번호 찾기 등에서 이메일 인증을 사용하게 될텐데, 이때 활용할 이메일 인증여부를 저장할 필드가 기존의 설계에는 존재하지 않아, 추가하였습니다.
- 엔티티에서 인증여부 필드는 notnull입니다. 인증되었는지 확인할 수 있는 중요한 필드라서 그렇습니다.
- DTO에서 인증여부 필드는 nullable입니다. 
- 멤버 테이블과 관련되서 작업하시는 분들은 적용 후 본인의 코드에 문제가 생기지 않았는지 확인해보셔야 할 것 같습니다.

:recycle: add: verified check field

---

src/main/java/com/honlife/core/app/controller/auth/AuthController.java
src/main/java/com/honlife/core/app/model/category/repos/InterestCategoryRepository.java
src/main/java/com/honlife/core/app/model/category/service/InterestCategoryService.java
src/main/java/com/honlife/core/app/model/common/BaseEntity.java
src/main/java/com/honlife/core/app/model/member/annotation/MemberEmailUnique.java
src/main/java/com/honlife/core/app/model/member/repos/MemberRepository.java
src/main/java/com/honlife/core/app/model/member/service/MemberService.java

- 회원가입 기능을 구현하였습니다. (인증코드 전송 로직 제외)
- `BaseEntity`를 상속받는 엔티티들에 해당되는 데이터가 변경될때 자동으로 감지되어 `update_at` 이 수정될 수 있도록 하였습니다.
- 기존에 존재하는 관심 카테고리를 수정하는 메소드를 추가하였습니다
- 새로운 관심 카테고리를 저장하는 메소드를 추가하였습니다.
- 회원가입 로직을 추가하였습니다
- 예외처리가 적용되어 3가지의 경우로 나누어집니다.
1. 이미 존재하며, 활성화된 계정의 이메일로 회원가입을 시도하는 경우
2. 이미 존재하는 계정이지만 이메일 인증이 완료되지 않았거나, 삭제된 계정의 이메일로 회원가입을 시도하는 경우
3. 신규 회원의 경우
- `MemberService`에서 이미 존재하는 이메일인지 판단하는 `Boolean`이 반환타입인 메서드를 기존 자동생성된 메서드를 수정하여 만들었습니다.
- `MemberService`에서 이메일 인증이 완료된 회원인지 판단하는 `Boolean`이 반환타입인 메서드를 생성하였습니다.
- 두 메서드 모두 회원 검증시 꼭 필요한 메서드라고 생각되며, 머지되었을때 기존에 작업하시던 브랜치에서 충돌이 없을지 확인하시길 바랍니다.

🚧 회원가입 로직 추가(메일 전송 로직 제외)

---

src/main/java/com/honlife/core/app/controller/routine/RoutineController.java

사용자 루틴 조회 API의 모킹 데이터를 날짜별로 다르게 제공하도록 개선했습니다.
기존에는 날짜가 바뀌어도 동일한 데이터가 반환되던 문제를 해결하여, 특정 날짜에는 다른 루틴 데이터를 제공합니다.
- 2025-07-16 날짜에 대해 별도의 모킹 데이터 추가
- 팀 미팅 참석, 기술 서적 읽기, 저녁 조깅 등 3개 루틴 데이터
- 기존 모킹 데이터를 다른 모든 날짜의 기본값으로 유지
- 날짜별 데이터 분기 처리를 통해 API 테스트 시 다양한 시나리오 확인 가능
- 특정 날짜(2025-07-16)에만 다른 데이터가 나오는지 확인
- 기존 날짜들은 여전히 기본 데이터가 정상적으로 반환되는지 확인
- 추후 더 많은 날짜별 데이터가 필요하면 쉽게 확장 가능한 구조인지 검토

[Swagger] 루틴 API - 2025.07.16 모킹 데이터 추가

---

src/main/java/com/honlife/core/app/controller/auth/AuthController.java
src/main/java/com/honlife/core/app/controller/auth/payload/SignupAdditionalRequest.java
src/main/java/com/honlife/core/app/controller/auth/payload/SignupBasicRequest.java
src/main/java/com/honlife/core/app/controller/auth/payload/SignupRequest.java
src/main/java/com/honlife/core/app/controller/auth/payload/VerifyEmailRequest.java
src/main/java/com/honlife/core/app/model/member/service/MemberService.java

- 프론트팀의 UI를 참고하여 회원가입 로직을 리팩토링 하고, 메일 전송 부분을 분리해 내었습니다.
- 현재 기본정보 입력후 이메일 인증 -> 추가정보(닉네임, 자취경력, 관심 카테고리)를 입력하는 형식으로 UI가 구성되어있어, 이메일 인증까지만 로직을 구현해두었습니다.(실제 메일 전송은 구현되지 않음)
- 추가정보 입력에 대해서는, 이메일 인증 완료된 시점에서 자동로그인이 되도록 하거나, 기본정보만 받고 이메일 인증 후에 로그인으로 돌아가도록 프론트팀과 추가적인 대화가 필요할 것 같습니다.
- 기존의 SignupRequest를 두개의 파일로 나누는 과정에서, Swagger 어노테이션들을 삭제하였습니다.
- 설명에 작성한 대로, 프론트팀의 회원가입 UI및, 이후 비밀번호 찾기때 이메일 인증코드 발송 요청을 대비하여 인증코드 전송 로직을 회원가입 로직에서 분리하였습니다.
- 추후 희의내용에따라, 회원가입 로직의 마지막에 이메일 인증코드 전송로직이 다시 생길 수 있습니다.
- 어차피 수정이 더 일어날 코드이기도 하고, 똥 싼 코드라 로직에 문제없는지만 살펴봐주시면 될 것 같습니다.

♻️ Refactor: 회원가입 로직, 이메일 전송 로직 분리

---

src/main/java/com/honlife/core/app/controller/badge/BadgeController.java

Badge 도메인의 전체 배지 조회 API(`GET /badges`)를 실제 데이터베이스와 연동하여 구현했습니다.
기존 하드코딩된 목업 데이터를 제거하고, 모든 배지의 사용자 획득 상태를 실시간으로 조회할 수 있도록 개선했습니다.
- getAllBadges 엔드포인트의 하드코딩된 목업 데이터를 실제 Service 연동으로 교체
- Stream 기반 DTO to Response 변환으로 효율적인 리스트 처리 구현
- 단일 배지 조회와 일관된 패턴 적용: 이메일 추출, 서비스 호출, 응답 매핑
- 모든 배지의 사용자 획득 상태를 실시간으로 조회할 수 있도록 구현
- 기존 API 계약을 유지하면서 내부적으로 실제 배지 및 회원 데이터와 연동
- **일관성 있는 구현**: 이미 구현된 단일 배지 조회(`GET /badges/{key}`)와 동일한 패턴을 사용하여 일관성을 유지했습니다.
- **효율적인 리스트 처리**: Stream API를 활용한 DTO to Response 변환으로 깔끔하고 효율적인 코드 구현했습니다.
- **실시간 데이터 조회**: 하드코딩된 데이터 대신 실제 데이터베이스에서 배지 목록과 사용자 획득 상태를 실시간으로 조회합니다.
- **기존 Service 활용**: 이미 구현된 `getAllBadgesWithMemberInfo(email)` 메서드를 그대로 활용하여 안정적인 구현을 보장했습니다.

Badges - 뱃지 전체 조회 기능 구현

---

src/main/java/com/honlife/core/app/controller/routine/RoutinePresetController.java
src/main/java/com/honlife/core/app/controller/routine/payload/RoutinePresetsResponse.java
src/main/java/com/honlife/core/app/model/routine/domain/RoutinePreset.java
src/main/java/com/honlife/core/app/model/routine/repos/RoutinePresetRepository.java
src/main/java/com/honlife/core/app/model/routine/service/RoutinePresetService.java

카테고리 id에 따라 루틴 프리셋 리스트를 반환하는 API를 만들었습니다.
스웨거 어노테이션을 삭제하였습니다.
카테고리 Id를 통해서 추천 루틴을 가져오는 API를 작성하였습니다.
RoutinePreset 엔티티에서 id가 정상적으로 생성되기 위해 SequenceGenerator의 name과 GeneratedValued의 generator를 바꾸었습니다.

Routine preset - get routine presets

---

src/main/java/com/honlife/core/app/controller/auth/AuthController.java
src/main/java/com/honlife/core/app/controller/auth/payload/DuplicationCheckRequest.java

- 이메일 중복 체크와 닉네임 중복 체크 API를 하나의 API로 합치는 것으로 결정이 되었기 때문에, 누락되어있던 닉네임 중복 체크 로직을 추가하였습니다.
- 닉네임 중복체크 로직을 추가하였습니다.

♻️ 이메일 or 닉네임 중복 체크 API 업데이트

---

src/main/java/com/honlife/core/app/controller/auth/AuthController.java
src/main/java/com/honlife/core/app/model/item/service/AdminItemService.java

- 회원가입과 이메일 전송 로직을 완전히 분리해달라는 요청이 있어서, 회원가입시 정보 저장후 이메일이 자동 전송되는 로직을 제거하였습니다.
- 회원가입 로직에서 이메일 전송 로직을 제거하였습니다.
- 현재 dev 브랜치의 AdminItemService 에서 생성자 하나가 빠져 에러가 뜨는 문제를 해결했습니다.
- 8시전까지 운영서버에 반영되어야 하는 항목입니다. 빠른 PR 부탁드립니다.

:ambulance: [긴급] 회원가입 이메일 전송 로직 제거

---

src/main/java/com/honlife/core/app/controller/badge/BadgeController.java
src/main/java/com/honlife/core/app/controller/badge/payload/BadgePageResponse.java
src/main/java/com/honlife/core/app/controller/badge/payload/BadgeResponse.java
src/main/java/com/honlife/core/app/controller/badge/payload/BadgeRewardResponse.java
src/main/java/com/honlife/core/app/model/badge/code/BadgeStatus.java

배지 모킹 서버 컨트롤러를 실제 구현 코드와 테스트 데이터에 맞게 업데이트했습니다. 
프론트엔드가 실제 API와 동일한 응답 구조로 개발할 수 있도록 모킹 데이터를 개선했습니다.
- 기존 모킹 데이터(`clean_bronze`, `cook_bronze` 등)를 실제 테스트 데이터 키(`CLEAN_BRONZE`, `COOK_BRONZE` 등)로 변경
- BadgeResponse 구조를 실제 구현에 맞게 수정 (`status`, `currentProgress`, `message` 필드 사용)
- 페이지네이션 지원을 위한 `BadgePageResponse` 구조로 응답 형태 변경
- 실제 포인트 정책에 맞게 BRONZE 배지 보상을 100포인트로 조정
- 8개 카테고리별 배지와 출석 배지를 포함한 다양한 상태(LOCKED/ACHIEVABLE/OWNED/EQUIPPED) 시나리오 제공
- 단건 조회 API 제거 (실제 구현에 존재하지 않음)
- 모킹 데이터가 실제 DB 테스트 데이터와 정확히 일치하는지 확인해주세요
- BadgeStatus enum과 페이지네이션 응답 구조가 실제 구현과 동일한지 검토 부탁드립니다
- 프론트엔드 개발 시 필요한 모든 배지 상태 시나리오가 포함되었는지 확인해주세요

🚑️[Swagger]  업적 - 업적 기능 수정에 따른 모킹 서버 수정

---

src/main/java/com/honlife/core/app/model/routine/domain/RoutineSchedule.java
src/main/java/com/honlife/core/app/model/routine/repos/RoutineScheduleRepositoryCustomImpl.java
src/main/java/com/honlife/core/app/model/routine/service/RoutineScheduleService.java
src/main/java/com/honlife/core/app/model/routine/service/RoutineService.java

- RoutineSchedule 에서 날짜 필드명이 date -> scheduleDate로 바뀜에 따라, 기존의 커밋내용에서 date로 사용되어 발생했던 필드명 불일치 문제 해소
- `scheduleDate` -> `scheduledDate` 로 엔티티의 필드명 의미를 좀더 명확하게 바꾸었습니다.
- 기존 `date` -> `scheduleDate`로 필드명이 바뀜에 따라 `RoutineScheduleRepositoryCustomImpl`에서 필드명 불일치로 발생하던 문제를 해결했습니다.
- 동일한 QClass가 서로 다른 변수명으로 초기화되어 사용되고 있던 것을 발견하여 중복된 QClass를 하나로 통일하였습니다. 
- 당장 급한 문제만 해결하다보니 DTO쪽은 수정하지 않았습니다.
- 컴파일 단계의 문제라, 이게 해결이 안되면 dev 실행자체가 안됩니다.

🚑  [Hotfix] 루틴 스케줄 필드명 불일치로 인한 컴파일 에러 해결

---

src/main/java/com/honlife/core/app/model/routine/service/RoutineScheduleService.java
src/main/java/com/honlife/core/infra/event/CommonEvent.java

- 루틴완료 API 에서 호출하는 서비스의 매서드에 퀘스트 진행도 추적을 위한 이벤트를 호출하는 로직을 추가하였습니다.
- 이벤트 객체에 builder 어노테이션을 추가하고, 기존의 매서드 내에서 필요한 정보들을 담아 이벤트를 발행하도록 하였습니다.

✨ 루틴 완료시에 퀘스트 진행도 추적을 위한 이벤트 발행

---

src/main/java/com/honlife/core/app/controller/member/MemberController.java
src/main/java/com/honlife/core/app/controller/member/MemberResponseWrapper.java
src/main/java/com/honlife/core/app/controller/member/payload/MemberBadgeResponse.java
src/main/java/com/honlife/core/app/model/member/repos/MemberBadgeRepositoryCustom.java
src/main/java/com/honlife/core/app/model/member/repos/MemberBadgeRepositoryCustomImpl.java
src/main/java/com/honlife/core/app/model/member/service/MemberBadgeService.java

멤버 정보를 보내는 API에 장착한 뱃지에 대한 정보도 추가하였습니다.
repository에 장착 뱃지 찾는 로직 추가함
멤버 조회 API에 장착 뱃지 추가하는 기능 구현함

Member - 멤버 정보에 장착한 뱃지 정보 추가

---

src/main/java/com/honlife/core/app/controller/notification/NotificationController.java
src/main/java/com/honlife/core/app/controller/notification/payload/NotificationPayload.java
src/main/java/com/honlife/core/app/model/notification/domain/Notification.java
src/main/java/com/honlife/core/app/model/notification/dto/NotificationDTO.java
src/main/java/com/honlife/core/app/model/notification/service/NotificationService.java

- 이메일 리마인드 알림 기능 구현을 하지 않기로 하였고, 퀘스트 관련 알람을 추가하기로 하여 해당 부분 반영했습니다.
- 기존 이메일 알림 필드를 퀘스트 알림으로 대체 하였습니다
- 새로운 알림 API와의 혼동을 방지하기위해 기존 알림설정 api주소를 수정하였습니다.

♻️  이메일 알람 필드 삭제 및 퀘스트 알람 필드 추가

---

src/main/java/com/honlife/core/app/controller/quest/payload/WeeklyQuestProgressResponse.java
src/main/java/com/honlife/core/app/model/point/service/PointPolicyService.java
src/main/java/com/honlife/core/app/model/quest/dto/MemberEventQuestDTO.java
src/main/java/com/honlife/core/app/model/quest/dto/MemberWeeklyQuestDTO.java
src/main/java/com/honlife/core/app/model/quest/service/EventQuestProgressService.java
src/main/java/com/honlife/core/app/model/quest/service/WeeklyQuestProgressService.java
src/main/resources/data.sql

- 퀘스트 조회시 보상이 함께 반환되지 않는 문제를 해결하였습니다.
- 현재 존재하는 퀘스트 테스트 데이터의 키값에 해당하는 포인트 정책이 없어, 해당 키값에 대한 포인트 정책들을 추가하였습니다.
- 더이상 사용되지 않는 코드들을 삭제하였습니다.
- 퀘스트 목록 응답시 포인트가 같이 반환되도록 하기위해 points 필드를 추가하였습니다.
- map 이제야 좀 익숙해지는듯

:ambulance: Hotfix :: 퀘스트목록 조회시 보상이 함께 반환되지 않는 문제 해결

---

src/main/java/com/honlife/core/app/controller/member/payload/MemberItemResponse.java
src/main/java/com/honlife/core/app/model/member/model/MemberItemDTOCustom.java
src/main/java/com/honlife/core/app/model/member/service/MemberItemService.java

회원아이템 반환 값 itemId 추가 하였습니다
✨ feat: Add id field to MemberItem response payload
- 회원 아이템을 조회 하고 그 결과 값으로 장착상태를 변경하는데 id 값이 없어서 
문제가 있다고 하여 DTO와 Response에 Id값을 추가하였습니다.
Swagger 문서에는 id 로 하드코딩 되어있어 해당 브랜치만 바꾸면 됩니다!!!

[긴급] 회원아이템 반환 값 추가 

---

src/main/resources/application-prod.properties

- DevOps서버에서 이메일 전송이 안되는 문제를 확인. 해결하였습니다.
- prod환경에서 smtp 포트로 587을 사용하도록 properties에 명시하였습니다. 
- smtp는 기본 25포트를 사용한다고 합니다.. 그런데 AWS같은 클라우드에서 25서버를 지원하지 않는 경우가 대다수이며, 심지어 AWS는 25포트 아웃바운드는 지원하지 않는다고 명시되어있다고도 하네요.

:ambulance: 인증 이메일 전송 안되는 문제 해결

---

src/main/java/com/honlife/core/app/controller/notification/NotifyController.java
src/main/java/com/honlife/core/app/controller/notification/payload/NotifyResponse.java
src/main/java/com/honlife/core/app/model/notification/code/NotificationType.java
src/main/java/com/honlife/core/app/model/notification/domain/NotifyList.java
src/main/java/com/honlife/core/app/model/notification/dto/NotifyListDTO.java

알림 목록 API 관련 초안을 작성하였습니다.
✨ feat: Add initial Swagger documentation for Notify API
- ERD 테이블 추가하였고 그걸 기반으로
`Entity` , `DTO`, `EnumType`, `Response`, `Controller` 를 작성하였습니다.
- 현재 단순히 ERD 기준으로 Entity 중심으로 추가한 것이고 
초안 작성 한거에 있어 Entity나 DTO가 잘못 작성 된게 있나 확인 차 올렸습니다!!!
✨ feat: Add Swagger API docs and annotations for Notify endpoints
- 읽지 않은 알림 목록 조회하는 API 추가하였고
- 전체적으로 주석 추가했습니다.
- 단건 읽음 전체 읽음에 대해서는 시나리오를 통해 좀 더 자세한 주석 추가하겠습니다

[Swagger] 알림 목록 API 관련 기능 작성
